name: "resnet34"
platform: "pytorch_libtorch"
max_batch_size : 8 
input [
  {
    name: "input__0"
    data_type: TYPE_FP32
    dims: [ 3, 768, 768 ]
  }
]
output [
  {
    name: "output__0"
    data_type: TYPE_FP32
    dims: [ -1 ]

  }
]

dynamic_batching { }
